### ISSUE TITLE
Compiling with Clang 13.0.0 fails

### ISSUE THREAD

**Issue by Bond-009** [cuberite/cuberite#5347]
Server OS: Linux
Cuberite Commit id: 7790ebc63b891668dbce8d4fe9c62f01a1f83fea

Compiling with Clang 13.0.0 fails

```
cuberite/lib/mbedtls/library/psa_crypto_cipher.c:267:12: error: parameter 'output_size' set but not used [-Werror,-Wunused-but-set-parameter]
    size_t output_size,
           ^
1 error generated.
make[2]: *** [lib/mbedtls/library/CMakeFiles/mbedcrypto.dir/build.make:748: lib/mbedtls/library/CMakeFiles/mbedcrypto.dir/psa_crypto_cipher.c.o] Error 1
```

**Comment by 12xx12** [comment]
This seems to be a problem of polarssl

Our branch is up to date with theirs

**Comment by tigerw** [comment]
Fixed upstream ARMmbed/mbedtls#4938 but awaiting their release

**Comment by 12xx12** [comment]
@tigerw there was a relese twlve days ago which fixes the bug

**Comment by bearbin** [comment]
Hopefully fixed by #5370, can you confirm @Bond-009

**Comment by Bond-009** [comment]
There are still more errors, see #5374

**Comment by Bond-009** [comment]
```
error: AST file was compiled with the target feature '-rtm' but the current translation unit is not
error: current translation unit is compiled with the target feature '+rtm' but the AST file was not
```
When compiling without any options

**Comment by 12xx12** [comment]
Is this issue resolved with the PR?

**Comment by Bond-009** [comment]
No, see my last comment

**Comment by KingCol13** [comment]
I just managed to compile with clang 13.0.0. My compilation issues seem to have been fixed in da0fdbe113e9b3a5254822a20a8ca2595cd661cb.

**Comment by Bond-009** [comment]
Master compiles fine now, tested release and debug.
