### ISSUE TITLE
experimental: Windows/MSVC build broken (three one-line fixes + remaining modules errors)

### ISSUE THREAD

**Issue by aidanvalero** [cuberite/cuberite#5642]
Tried to build experimental (cee49da3b) on Windows to runtime-test #5627. It doesn't compile with VS 2022 Build Tools 17.14.34 (MSVC toolset 14.44.35207), and CI is red on all three platforms at the branch tip, so posting what I found.

Three small blockers, each verified locally (the build proceeds past all of them with these changes):

1. `StartAsService.h`: char* into LPWSTR. SetFlags.cmake forces `UNICODE`/`_UNICODE`, so `SERVICE_TABLE_ENTRY.lpServiceName` is `LPWSTR`:

```
StartAsService.h(24,31): error C2440: 'initializing': cannot convert from 'char *' to 'LPWSTR'
```

```diff
-			{ reinterpret_cast<char *>(&g_ServiceName), (LPSERVICE_MAIN_FUNCTION)serviceMain<UniversalMain> },
+			{ reinterpret_cast<LPTSTR>(&g_ServiceName), (LPSERVICE_MAIN_FUNCTION)serviceMain<UniversalMain> },
```

That cast is just the minimal compile unblock. The cleaner fix is making `g_ServiceName` a `wchar_t[]` like master's copy of this file already has; experimental's version regressed relative to master here.

2. `WinStackWalker.cpp`: mixed A/W API calls. The file calls `GetFileVersionInfoSizeA` (explicit A) two lines above charset-macro `GetFileVersionInfo`/`VerQueryValue`, which expand to the W variants under UNICODE and won't take the `CHAR*` buffers:

```
WinStackWalker.cpp(603,11): error C2664: 'BOOL GetFileVersionInfoW(LPCWSTR,DWORD,DWORD,LPVOID)': cannot convert argument 1 from 'CHAR *' to 'LPCWSTR'
```

```diff
-						if (GetFileVersionInfo(szImg, dwHandle, dwSize, vData) != 0)
+						if (GetFileVersionInfoA(szImg, dwHandle, dwSize, vData) != 0)
 						{
 							UINT len;
-							TCHAR szSubBlock[] = _T("\\");
-							if (VerQueryValue(vData, szSubBlock, (LPVOID*)&fInfo, &len) == 0)
+							CHAR szSubBlock[] = "\\";
+							if (VerQueryValueA(vData, szSubBlock, (LPVOID*)&fInfo, &len) == 0)
```

3. `MobSpawner.cpp:8`: stray double semicolon on a module import, which MSVC rejects outright:

```
MobSpawner.cpp(8,21): error C7586: a 'import' directive must end with a ';' on the same line
```

```diff
-import Block.Leaves;;
+import Block.Leaves;
```

After those three, the C++20 modules code still fails with a deeper set of errors I didn't attempt, e.g.:

```
Blocks/BlockLever.cppm(30,15): error C2027: use of undefined type 'cChunkInterface'
Blocks/BlockLever.cppm(31,24): error C2661: 'Block::Lever::Lever': no overloaded function takes 1 arguments
Blocks/BlockLilypad.cppm(39,21): error C2027: use of undefined type 'cChunk'
Blocks/BlockPressurePlate.cppm(54,20): error C2440: 'type cast': cannot convert from 'BlockType' to 'int'
Items/ItemDoor.cppm(148,46): while trying to match the argument list '(const Vector3i)'
```

These look like the module purview not seeing the class definitions it needs, which is a call for whoever owns the migration rather than a drive-by fix.

Can PR items 1-3 if wanted. For what it's worth, after working around all this on Linux instead, #5627 runtime-tests correctly on this branch (details on the PR).
