### PR TITLE
Fix FreeBSD build by including signal.h

### PR DESCRIPTION
**Pull request by mjhanninen**
On FreeBSD the build dies due to missing `signal.h`:

    [ 97%] Building CXX object src/CMakeFiles/MCServer.dir/Root.cpp.o
    /home/matti/cuberite/src/Root.cpp:301:51: error: use of undeclared identifier 'SIGKILL'
                    if (pthread_kill(m_InputThread.native_handle(), SIGKILL) != 0)

Dependency on `signal.h` was introduced by #2427.

This PR fixes the build. However I wonder whether these POSIX headers should be included in less a case-by-case manner. I'm not a pro on that front so I couldn't tell.

### CODE REVIEW

**Comment by worktycho** [comment]
I agree with you that a more general solution is necessary. How about using the  `__unix__` macro instead?

**Comment by mjhanninen** [comment]
Yep, I guess it is less wrong. According to [this SO answer](http://stackoverflow.com/a/11351171) the following is a reasonable way of detecting a POSIX system:

    #if defined(__unix__) || (defined(__APPLE__) && defined(__MACH__))
    ...
    #endif

**Comment by worktycho** [comment]
That seems reasonable.

**Comment by madmaxoft** [comment]
Looks good, squash and rebase onto current master and we can merge.
