### ISSUE TITLE
Compile error with GCC 15.1.0

### ISSUE THREAD

**Issue by ppp7032** [cuberite/cuberite#5614]
Client version: N/A
Server OS: Debian 13
Cuberite Commit id: Latest download from [website](https://download.cuberite.org/source/Cuberite.tar.gz) as of time of submission.

### Expected behavior
Compile succeeds

### Actual behavior
Compile fails with
```
/home/linuxbrew/.linuxbrew/Cellar/gcc/15.1.0/include/c++/15/ext/concurrence.h:257:32: error: cannot convert '<brace-enclosed initializer list>' to 'unsigned int' in initialin
  257 |     __gthread_cond_t _M_cond = __GTHREAD_COND_INIT;
      |                                ^~~~~~~~~~~~~~~~~~~
```

### Steps to reproduce the behavior
Attempt to Compile with GCC 15.1.0.

### Server log
N/A
Relevant part of server log
N/A

**Comment by MightyFilipns** [comment]
Can you try compiling with the latest master branch, and if that fails, try compiling the experimental branch?

**Comment by ppp7032** [comment]
I had tried using homebrew's cmake (`v4.1.0`) but that failed during the `cmake` step. After that, I tried `v3.31.6` from the Debian stable repo. This time, the `cmake` step completed with only deprecation warnings.

Is the source tarball from the website not the latest artefact from the master branch?

Having fetched the source code via Git, the same error exists in both master and experimental branches.

The error was much easier to see when I compiled without multi-threading. Here's the error from the experimental branch:
```
In file included from /home/linuxbrew/.linuxbrew/Cellar/gcc/15.1.0/include/c++/15/x86_64-pc-linux-gnu/bits/gthr-default.h:35,
                 from /home/linuxbrew/.linuxbrew/Cellar/gcc/15.1.0/include/c++/15/x86_64-pc-linux-gnu/bits/gthr.h:157,
                 from /home/linuxbrew/.linuxbrew/Cellar/gcc/15.1.0/include/c++/15/ext/atomicity.h:37,
                 from /home/linuxbrew/.linuxbrew/Cellar/gcc/15.1.0/include/c++/15/bits/locale_classes.h:43,
                 from /home/linuxbrew/.linuxbrew/Cellar/gcc/15.1.0/include/c++/15/locale:43,
                 from /home/ppp7032/Downloads/cuberite/lib/fmt/include/fmt/format-inl.h:21,
                 from /home/ppp7032/Downloads/cuberite/lib/fmt/src/format.cc:8:
/home/linuxbrew/.linuxbrew/Cellar/gcc/15.1.0/include/c++/15/ext/concurrence.h:257:32: error: cannot convert '<brace-enclosed initializer list>' to 'unsigned int' in initialization
  257 |     __gthread_cond_t _M_cond = __GTHREAD_COND_INIT;
      |                                ^~~~~~~~~~~~~~~~~~~
/home/linuxbrew/.linuxbrew/Cellar/gcc/15.1.0/include/c++/15/bits/std_mutex.h:208:32: error: cannot convert '<brace-enclosed initializer list>' to 'unsigned int' in initialization
  208 |     __gthread_cond_t _M_cond = __GTHREAD_COND_INIT;
      |                                ^~~~~~~~~~~~~~~~~~~
```

**Comment by MightyFilipns** [comment]
Master currently has some outdated libraries that fail with CMake 4.0 and later. These are fixed on experimental.
Maybe this is caused by a bug fixed in GCC 15.2.1?

**Comment by ppp7032** [comment]
> Master currently has some outdated libraries that fail with CMake 4.0 and later.

That's odd because the Artix compilation that worked was of the master branch.

**Comment by ppp7032** [comment]
Googling the error leads to [this](https://github.com/orgs/Homebrew/discussions/6193) top result. I think it's safe to say this is a homebrew-related issue. Sorry for being trigger-happy with the issue.
